# Generated by Django 2.2.10 on 2021-02-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='iupdatedate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
