# Generated by Django 2.2.10 on 2021-02-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20210219_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='kforeverholdyn',
            field=models.BooleanField(default=True),
        ),
    ]
