# Generated by Django 2.2.10 on 2021-02-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20210220_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystocks',
            name='kforeverholdyn',
            field=models.BooleanField(default=False),
        ),
    ]
